### ISSUE TITLE
create figma design prototypes

### ISSUE THREAD

**Issue by samymsa** [HybridPlanner/frontend#1]
- Meeting creation form
   - Attendees (list of emails)
   - Start date and time
- Dashboard
  - My past meetings
  - My upcoming meetings
- Waiting page
  - "hh::mm::ss left before the meeting"

**Comment by FranckG28** [comment]
Link to [figma prototype](https://www.figma.com/file/7mtlLKhY9RdA05wriAVKGI/HybridPlanner-prototypes?node-id=42%3A12540&t=er708WuAFjg9Errc-1)
