### ISSUE TITLE
Add waiting page

### ISSUE THREAD

**Issue by samymsa** [HybridPlanner/frontend#22]
- [x] Create Figma design
- [x] Implement waiting page: `/meeting/{id}`
- [x] If meeting has not started yet: Display waiting message; Display Join button as disabled.
- [ ] If meeting has already started: redirect

**Comment by FranckG28** [comment]
![Image](https://github.com/HybridPlanner/frontend/assets/19238963/83717d77-bca6-41ab-9e23-3b1707a14854)
