### ISSUE TITLE
Authentication Page

### ISSUE THREAD

**Issue by samymsa** [HybridPlanner/frontend#4]
- [x] Figma
- [ ] Implementation
    - [ ] Frontend UI
    - [ ] Backend logic

**Comment by FranckG28** [comment]
![Image](https://user-images.githubusercontent.com/19238963/232050109-858f5c18-e2d6-4156-b517-55fab02ef041.png)



![Image](https://user-images.githubusercontent.com/19238963/232050141-a4330cbc-1fd5-4651-b450-d12919f37f7c.png)
